### ISSUE TITLE
[Review] JOSS Review Feedback

### ISSUE THREAD

**Issue by qpmnguyen** [julia-wrobel/registr#38]
Hi all, 

This is the feedback issue for the current JOSS submission [here](https://github.com/openjournals/joss-reviews/issues/2964). 

I think this is a wonderful submission and I would recommend it for acceptance for publication in JOSS. The package was really easy to use and is well documented and supported, where I especially appreciate that vignettes list all the important user-facing functions. Sometimes, packages can have too many functions and it's hard to know where to start. Following are just some minor recommendations I have, mostly relating to documentation.  

1. I would appreciate a bit more discussion on the choice of distribution family other than gaussian and binomial. I understand that these are the two common types of outcomes that users might face, but the package does support a larger number of available families that should be featured. 
2. There is a section in the vignette that includes a discussion on the differences in computational time between using an analytical versus numerical gradient. I think that the discussion should include some information as to when a user might want to use a numerical gradient versus an analytical one, given improvements in computational time. 
3. Relatedly, I think the package would also benefit from having a bit more details on computational time performance. Users might not really know what is the limiting factor for computational time for the package (Sample size? Number of time points?). The authors can include computational time for a typical experiment a user might encounter. 
4. Given that the package already has real data bundled, it would be interesting to see in the vignette a short analysis of that data set.  
5. While I understand that this package implements a novel statistical approach, it would also be great to list packages that are in the same space. Right now the packages referenced in the text are alternative/related implementation of specific parts of the algorithm, rather than a survey of other existing software in R to analyze functional data. 

That said, this was a great submission. Feel free to close this issue at your convenience.

**Comment by bauer-alex** [comment]
Thank you very much for the feedback.

Here is what I changed in the package documentation and the paper regarding your recommendations:

1. I adapted Section 2 in the main vignette a bit to make it clearer which distribution can be used in what data situation. Given these changes, I think that the family argument is now documented adequately well.
2. Maybe there was a misunderstanding regarding the use of the analytical version of the gradient. The analytical version of the gradient should always be used when available, since it implements the explicit gradient for the distribution family which otherwise would have to be estimated numerically (i.e., less accurately and less computationally efficient). I see that this might not have been documented perfectly well, leading to some confusion. I changed Section 6 in the main vignette to better explain what we try to say about the difference between the two gradients. Now it should be clear.
3. I added the runtimes for a larger data example in Section 6 in the main vignette.
4. I added such a subsection relating to the dataset at the end of Section 3 in the incomplete curves vignette.
5. Thank you for this valuable point! There is now a new paragraph at the end of Section 1 in the paper (see [main issue](https://github.com/openjournals/joss-reviews/issues/2964)) to list relevant alternative packages.
